services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dbstudentlink'
      - 'MYSQL_USER=wiseowls'
      - 'MYSQL_PASSWORD=Wiseowls2025'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
      
    ports:
      - '3307:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    restart: always
    
volumes:
    mysql-data: